services:
  - type: web
    name: bongo-ai
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: SESSION_ID
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: OWNER_NUMBER
        sync: false
      - key: BOT_NAME
        value: "BoNGo AI"
      - key: PREFIX
        value: "."
